package com.bbva.iso8583lib.module

enum class EReason {
    NONE,
    NOT_INIT_MODULE,
    SERVICE_CONNECTION,
    SERVICE_DISCONNECT,
    IO_EXCEPTION,
    SEND_TX_SUCCESS,
    SEND_TX_FAIL,
    RECEIVE_TX_SUCCESS,
    RECEIVE_TX_FAIL,
    PREPARE_SUCCESS,
    INIT_SUCCESS,
    PRECONDITION_SUCCESS,
    RESPONSE_SUCCESS,
    RESPONSE_FAIL,
    OPERATION_FAIL,
    OPERATION_SUCCESS,
    SERVER_CONNECT_SUCCESS,
    SERVER_CONNECT_FAIL,
    SERVER_DISCONNECT_SUCCESS,
    SERVER_DISCONNECT_FAIL,
    PACK_SPECIFIC_FIELD_SUCCESS,
    PACK_SPECIFIC_FIELD_FAIL,
    UNPACK_SPECIFIC_FIELD_SUCCESS,
    UNPACK_SPECIFIC_FIELD_FAIL
}